CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;

CREATE USER upids_admin WITH PASSWORD 'upids_admin_123';
GRANT CONNECT ON DATABASE upids TO upids_admin;
GRANT USAGE ON SCHEMA public TO upids_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO upids_admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO upids_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO upids_admin;
